table dim_sede
	lineageTag: 7f1d2836-1601-43e6-8360-3f4f4d5cb5ed

	column id_sede
		dataType: int64
		formatString: 0
		lineageTag: 218d99cd-4fca-4ba6-94e9-ad8a0d180ed4
		summarizeBy: none
		sourceColumn: id_sede

		annotation SummarizationSetBy = Automatic

	column nombre_sede
		dataType: string
		lineageTag: 23a5f639-9c58-4cfb-ac56-bd9e216845a7
		summarizeBy: none
		sourceColumn: nombre_sede

		annotation SummarizationSetBy = Automatic

	column ubicacion_sede
		dataType: string
		lineageTag: 97e600cc-048c-4031-99bd-08ba5d2f276f
		summarizeBy: none
		sourceColumn: ubicacion_sede

		annotation SummarizationSetBy = Automatic

	partition dim_sede = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Luis Nativi\Desktop\VentasVehiculos.xlsx"), null, true),
				    dim_sede_Table = Source{[Item="dim_sede",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_sede_Table,{{"id_sede", Int64.Type}, {"nombre_sede", type text}, {"ubicacion_sede", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

