table Dim_Calendario
	lineageTag: 59b33dd4-8819-4435-a27f-9679dbc2d5c4

	column Fecha
		dataType: dateTime
		formatString: Long Date
		lineageTag: e44df6a5-569b-48ba-b363-0fbcbd2987a7
		summarizeBy: none
		sourceColumn: Fecha

		variation Variation
			isDefault
			relationship: 554453d9-00dc-40ee-b814-0379fa83a1b0
			defaultHierarchy: LocalDateTable_531e4ed4-a9e2-4f43-a740-b8d25efd1514.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Año
		dataType: int64
		formatString: 0
		lineageTag: f7ed460c-bc14-4b81-8db7-1eb9a6d1653b
		summarizeBy: sum
		sourceColumn: Año

		annotation SummarizationSetBy = Automatic

	column Semana
		dataType: int64
		formatString: 0
		lineageTag: 678b30de-b603-4638-a70c-e7eeceb2406a
		summarizeBy: sum
		sourceColumn: Semana

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: string
		lineageTag: b2119989-8aa3-4a30-a7e2-c30d83ea7842
		summarizeBy: none
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column 'Numero Mes'
		dataType: int64
		formatString: 0
		lineageTag: ba4bb13c-7616-4c81-9a82-5720c46fd2d0
		summarizeBy: sum
		sourceColumn: Numero Mes

		annotation SummarizationSetBy = Automatic

	column datekey
		dataType: int64
		formatString: 0
		lineageTag: 958fa27c-9006-4aa6-8c1e-c5aa31924609
		summarizeBy: none
		sourceColumn: datekey

		annotation SummarizationSetBy = Automatic

	partition Dim_Calendario = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Luis Nativi\Desktop\VentasVehiculos.xlsx"), null, true),
				    Dim_Calendario_Table = Source{[Item="Dim_Calendario",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Calendario_Table,{{"Fecha", type date}, {"Año", Int64.Type}, {"Semana", Int64.Type}, {"Mes", type text}, {"Numero Mes", Int64.Type}, {"datekey", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

