table dim_canal
	lineageTag: 6bb5680b-86ae-47f4-b8ce-b5a47a4477d1

	column id_canal
		dataType: int64
		formatString: 0
		lineageTag: fe3188f6-d7a9-4826-b335-aae0b9432653
		summarizeBy: none
		sourceColumn: id_canal

		annotation SummarizationSetBy = Automatic

	column tipo_canal
		dataType: string
		lineageTag: 54a3d593-1352-47eb-ac99-f108684d9c3d
		summarizeBy: none
		sourceColumn: tipo_canal

		annotation SummarizationSetBy = Automatic

	column canal
		dataType: string
		lineageTag: f38184e7-d61d-43e7-b092-aebb6281018f
		summarizeBy: none
		sourceColumn: canal

		annotation SummarizationSetBy = Automatic

	partition dim_canal = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Luis Nativi\Desktop\VentasVehiculos.xlsx"), null, true),
				    dim_canal_Table = Source{[Item="dim_canal",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_canal_Table,{{"id_canal", Int64.Type}, {"tipo_canal", type text}, {"canal", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

