table dim_vehiculo
	lineageTag: 15264125-53a3-44bf-a9f4-670da069f682

	column id_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: d99b4f26-c8e6-40a1-9ba0-45b4334ff930
		summarizeBy: none
		sourceColumn: id_vehiculo

		annotation SummarizationSetBy = Automatic

	column marca_vehiculo
		dataType: string
		lineageTag: a9770c50-e878-498c-aa74-80361d3d36a9
		summarizeBy: none
		sourceColumn: marca_vehiculo

		annotation SummarizationSetBy = Automatic

	column modelo_vehiculo
		dataType: string
		lineageTag: 875b6e0f-9988-4594-88b3-98540774ea4a
		summarizeBy: none
		sourceColumn: modelo_vehiculo

		annotation SummarizationSetBy = Automatic

	column tipo_vehiculo
		dataType: string
		lineageTag: c34c030a-be9c-4f88-b2ac-50639ca8532f
		summarizeBy: none
		sourceColumn: tipo_vehiculo

		annotation SummarizationSetBy = Automatic

	column año_vehiculo
		dataType: int64
		formatString: 0
		lineageTag: 1cd0cfb6-119a-47b5-a4e8-b5ade75a626a
		summarizeBy: none
		sourceColumn: año_vehiculo

		annotation SummarizationSetBy = Automatic

	column 'total ventas modelo' = COUNTROWS(Fact_Ventas)
		formatString: 0
		lineageTag: c71c1087-e372-4325-bbfc-6257424abcee
		summarizeBy: none

		annotation SummarizationSetBy = Automatic

	partition dim_vehiculo = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Luis Nativi\Desktop\VentasVehiculos.xlsx"), null, true),
				    dim_vehiculo_Table = Source{[Item="dim_vehiculo",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dim_vehiculo_Table,{{"id_vehiculo", Int64.Type}, {"marca_vehiculo", type text}, {"modelo_vehiculo", type text}, {"tipo_vehiculo", type text}, {"año_vehiculo", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

