table Dim_Vendedor
	lineageTag: 9cd9b80a-c201-408a-a660-5c7590460b07

	column ID_Vendedor
		dataType: int64
		formatString: 0
		lineageTag: 62f46282-dade-4481-b9ac-a5a0c28b8b3b
		summarizeBy: none
		sourceColumn: ID_Vendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: a7ba3f00-7ef0-45b4-9c7f-5d89cbac7626
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column fecha_nacimiento
		dataType: dateTime
		formatString: General Date
		lineageTag: 8aebbb42-eb51-4365-8a12-239e07a9db99
		summarizeBy: none
		sourceColumn: fecha_nacimiento

		variation Variation
			isDefault
			relationship: 2fc6f37d-5138-4425-b975-d8cd5ef4e629
			defaultHierarchy: LocalDateTable_aea47757-ddf6-4422-92c7-f45782936dbb.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

	column Foto
		dataType: string
		lineageTag: 9a6f1129-811b-4971-9111-6f0468a5d5af
		summarizeBy: none
		sourceColumn: Foto

		annotation SummarizationSetBy = Automatic

	partition Dim_Vendedor = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Luis Nativi\Desktop\VentasVehiculos.xlsx"), null, true),
				    Dim_Vendedor_Table = Source{[Item="Dim_Vendedor",Kind="Table"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(Dim_Vendedor_Table,{{"ID_Vendedor", Int64.Type}, {"Vendedor", type text}, {"fecha_nacimiento", type datetime}, {"Foto", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

